### ISSUE TITLE
SCTD数据下载

### ISSUE THREAD

**Issue by xueweili** [freepoet/SCTD#1]
您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
这是我的邮箱 569975634@qq.com

**Comment by tyutnwpuzw** [comment]
您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
这是我的邮箱 1275701124@qq.com    如果您看到了在这里回复也可以

**Comment by MingqiangNing** [comment]
发件人: tyutnwpuzw ***@***.***>
发送时间: 2023年3月4日 20:54
收件人: freepoet/SCTD ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [freepoet/SCTD] SCTD数据下载 (Issue #1)


您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
这是我的邮箱 ***@***.******@***.***> 如果您看到了在这里回复也可以

**Comment by destory-skywolf** [comment]
您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
这是我的邮箱514876730@qq.com

**Comment by ryikl** [comment]
您好，之前有幸拜读过您这篇论文，也使用过数据集，并在发表的论文中引用了您的文章。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
另外，论文中也有关于分类的实验，我也想获取一下SCTD **分类** 数据集
非常感谢
这是我的邮箱m18790628040@163.com，再次感谢

**Comment by yy721** [comment]
您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
这是我的邮箱1562000916@qq.com

**Comment by freepoet** [comment]
刚看到，目前github打不开，我今明天上传到github，你关注下
________________________________
发件人: yy721 ***@***.***>
发送时间: 2024年3月19日 20:15
收件人: freepoet/SCTD ***@***.***>
抄送: Mingqiang Ning ***@***.***>; Comment ***@***.***>
主题: Re: [freepoet/SCTD] SCTD数据下载 (Issue #1)


您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
***@***.******@***.***>

―

**Comment by MingqiangNing** [comment]
已经上传至Github
________________________________
发件人: yy721 ***@***.***>
发送时间: 2024年3月19日 20:15
收件人: freepoet/SCTD ***@***.***>
抄送: Mingqiang Ning ***@***.***>; Comment ***@***.***>
主题: Re: [freepoet/SCTD] SCTD数据下载 (Issue #1)


您好, 最近有幸拜读您这边论文，觉得很有意思，想要复现，但是在下载SCTD数据时遇到了问题。
您论文中说SCTD总共497张图，但是数据下载后只有357张图，请问如何获得全部SCTD数据
非常感谢
***@***.******@***.***>

―
