### ISSUE TITLE
SCTD2.0 dataset

### ISSUE THREAD

**Issue by sensoryu** [freepoet/SCTD#11]
Dear Author:
        Thanks for your great work! However, SCTD2.0 seems to be broken and unable to decompress. Would it be convenient for you to send me a copy? My email address is shenxingyu17@alumni.nudt.edu.cn.

**Comment by MingqiangNing** [comment]
The dataset has been sent via my QQ email, please check it.
________________________________
发件人: Xingyu Shen ***@***.***>
发送时间: 2024年11月12日 21:11
收件人: MingqiangNing/SCTD ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MingqiangNing/SCTD] SCTD2.0 dataset (Issue #11)


Dear Author:
Thanks for your great work! However, SCTD2.0 seems to be broken and unable to decompress. Would it be convenient for you to send me a copy? My email address is ***@***.******@***.***>.

―
