### ISSUE TITLE
SCTD2.0文件损坏

### ISSUE THREAD

**Issue by RussellYan** [freepoet/SCTD#12]
亲爱的作者，非常感谢您之前的回复。
我下载了SCTD 2.0，但是该文件已损坏，无法解压缩。
请问您方便将SCTD2.0发送至邮箱[1043494739@qq.com]吗，不胜感激！

**Comment by MingqiangNing** [comment]
已发送，请查收

**Comment by jichenghao666** [comment]
亲爱的作者，我下载了SCTD 2.0，但是该文件已损坏，无法解压缩。
请问您方便将SCTD2.0发送至邮箱[[1395594643@qq.com]吗，不胜感激！还有一个问题，这个数据集包含哪些种类

**Comment by MingqiangNing** [comment]
Shipwreck. Human. Aircraft.
________________________________

**Comment by jichenghao666** [comment]
Dear [Author/Team],
 
I would like to ask whether there are any duplicated or overlapping images between SCTD1.0 and SCTD2.0. Understanding the extent of overlap would help ensure proper data splitting and avoid data leakage in model training and evaluation.
 
Thank you in advance for your clarification.



12019054020姬成昊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MingqiangNing/SCTD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年5月20日(星期二) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MingqiangNing/SCTD] SCTD2.0文件损坏 (Issue #12)



 MingqiangNing left a comment (MingqiangNing/SCTD#12)

**Comment by MingqiangNing** [comment]
删除了SCTD2.0中一些低质量的图片就得到SCTD1.0，所以SCTD1.0是2.0的子集。
________________________________
