### ISSUE TITLE
请问如何引用您的工作？另外有没有2.0的数据集呀？

### ISSUE THREAD

**Issue by HDUyiming** [freepoet/SCTD#13]
我的邮箱是cuiyiming@hdu.edu.cn。感谢您为声纳社区做出的宝贵贡献，如何可以的话，我想在未来的工作中引用您的工作

**Comment by MingqiangNing** [comment]
Thanks for your affirmation and you can cite the following papers if they are helpful to you.
1. P. Zhang, J. Tang, H. Zhong, M. Ning, D. Liu and K. Wu, "Self-Trained Target Detection of Radar and Sonar Images Using Automatic Deep Learning," in IEEE Transactions on Geoscience and Remote Sensing, vol. 60, pp. 1-14, 2022, Art no. 4701914, doi: 10.1109/TGRS.2021.3096011.
2. M. Ning, J. Tang, H. Wu, H. Zhong and M. Ma, "An Efficient Subswath-Subband Chirp Z-Transform Algorithm for Multiple-Receiver SAS Considering the Differential Range Curvature," in IEEE Transactions on Geoscience and Remote Sensing, doi: 10.1109/TGRS.2025.3550427.
SCTD 2.0 Dataset has been sent via my qq email. If there are any issues with the dataset, please feel free to contact me.
