### ISSUE TITLE
The number of samples downloaded is inconsistent with that in the paper

### ISSUE THREAD

**Issue by oisudfoishjf** [freepoet/SCTD#5]
Dear author, it is stated in the paper that SCTD data set contains a total of 596 samples of 3 types of targets, but only 357 samples after SCTD download, may I ask which is the correct sample number? Look forward to your reply, thank you.

**Comment by MingqiangNing** [comment]
357 is the samples' number of the original SCTD dataset, and 596 is that of the latest SCTD 2.0 dataset. 596 is correct in the paper.
