### ISSUE TITLE
The SCTD 2.0 file can't be decompressed

### ISSUE THREAD

**Issue by hahahahaha20250325** [freepoet/SCTD#7]
Dear Author,
 I have come across your paper and found it to be excellent. However, I encountered an issue when attempting to use the SCTD2.0 file from the dataset, as it seems to be unusable. Could you kindly resend it? Thank you very much. My email is: 2019310241@bipt.edu.cn.

**Comment by freepoet** [comment]
url: https://pan.baidu.com/s/1HUqHYrzwD1KfUrRgC3einA?pwd=c5gp
code:c5gp
If it works well, please give this dataset a star on github.
Thanks.


________________________________
发件人: hahahaha2019310241 ***@***.***>
发送时间: 2024年10月8日 13:50
收件人: freepoet/SCTD ***@***.***>
抄送: Subscribed ***@***.***>
主题: [freepoet/SCTD] The SCTD 2.0 file can't be decompressed (Issue #7)


Dear Author,
I have come across your paper and found it to be excellent. However, I encountered an issue when attempting to use the SCTD2.0 file from the dataset, as it seems to be unusable. Could you kindly resend it? Thank you very much. My email is: ***@***.******@***.***>.

―

**Comment by hahahaha2019310241** [comment]
Thank you very much. I wish the best！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Mingqiang&nbsp;Ning"; 
Date: 2024年10月9日(星期三) 上午9:34
To: "freepoet/SCTD"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [freepoet/SCTD] The SCTD 2.0 file can't be decompressed (Issue #7)

&nbsp;


 url: https://pan.baidu.com/s/1HUqHYrzwD1KfUrRgC3einA?pwd=c5gp 
 code:c5gp 
 If it works well, please give this dataset a star on github. 
 Thanks. 
 
 
 ________________________________ 
 发件人: hahahaha2019310241 ***@***.***&gt; 
 发送时间: 2024年10月8日 13:50 
 收件人: freepoet/SCTD ***@***.***&gt; 
 抄送: Subscribed ***@***.***&gt; 
 主题: [freepoet/SCTD] The SCTD 2.0 file can't be decompressed (Issue #7) 
 
 
 Dear Author, 
 I have come across your paper and found it to be excellent. However, I encountered an issue when attempting to use the SCTD2.0 file from the dataset, as it seems to be unusable. Could you kindly resend it? Thank you very much. My email is: ***@***.******@***.***&gt;. 
 
 ―
