### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by hahahahaha20250325** [freepoet/SCTD#8]
Hello, I found that there are only 497 pictures in CSTD 2.0 data set, which does not consistent with the 596 in the paper. Why is this?Look forward to your reply, thank you.

**Comment by MingqiangNing** [comment]
497 images contain 596 targets, not 596 images.

**Comment by hahahahaha20250325** [comment]
Thank you very much, and good luck!

**Comment by hahahahaha20250325** [comment]
Thank you very much, and good luck!
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Mingqiang&nbsp;Ning"; 
Date: 2024年10月16日(星期三) 下午5:24
To: "freepoet/SCTD"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [freepoet/SCTD] Dataset problem (Issue #8)

&nbsp;


 
497 images contain 596 targets, not 596 images.
