### ISSUE TITLE
SCTD2.0

### ISSUE THREAD

**Issue by Yourheads** [freepoet/SCTD#9]
The SCTD2.0 dataset cannot be downloaded. Is there a problem with the upload you made?

**Comment by MingqiangNing** [comment]
What is your email address? I will send the file to your email.

**Comment by Yourheads** [comment]
liuyu@s.dlu.edu.cn
This is my email. Thank you for providing the dataset

> What is your email address? I will send the file to your email.

**Comment by MingqiangNing** [comment]
The dataset has been sent.
